import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Source_Serif_4 } from "next/font/google";
export const metadata: Metadata = {
  title: "OneRide",
  description: "Generated by create next app",
};

const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // All available weights
  variable: "--font-source-serif",
  display: "swap",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sourceSerif.variable} antialiased`}
      suppressHydrationWarning
    >
      <head />
      <body className="overflow-x-hidden scroll-smooth!">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
